name: stat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  fixnum: ^1.1.1
  protobuf: ^3.1.0
  intl: ^0.20.1
  flutter_svg: ^2.0.16



  cupertino_icons: ^1.0.8
  carousel_slider_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  assets:
    - assets/images/
  fonts:
    - family: Steppe
      fonts:
        - asset: assets/fonts/Steppe-Thin.ttf
    - family: Steppe-Medium
      fonts:
        - asset: assets/fonts/Steppe-Medium.ttf
    - family: Steppe-Regular
      fonts:
        - asset: assets/fonts/Steppe-Regular.ttf


  uses-material-design: true